language: node_js
node_js:
  - '8'
  - '10'
  - lts/*
  - node
sudo: false
cache:
  directories:
    - node_modules
before_script:
  - test ! -d node_modules || npm prune
scripts:
  - npm run test
  - npm run build
after_script:
  - test $TRAVIS_NODE_VERSION != '10' && sonar-scanner
notifications:
  email:
    recipients:
    - dragos.cirjan+glasswingjs@gmail.com
    on_success: never
    on_failure: always
addons:
  sonarcloud:
    organization: "glasswingjs"
    token:
      secure: "oAFo9iXWZxj/qj8j2vg8UIOYpOS1LpeIik618cUt6kH30G9ZfGpXydkK1eqOajFxacENg+oIkuu9ibjUKaOGNMId490eeTZitRnYPvm9XiV7MHbRESo4doaURFrvNMLlKElb9KRK8+mjq5QEBzIePDn+ImO27k60RMQ/Dzw45n0+1haIRW6g9XUlav8K1INFKHpHN3IIDT+Rrh8NuMjTKnoEh+xYlmhtLfRMQRXhlvpOlg+a4GUdVPyQgEf+aooQBBJhY9DZOzD3NtPRvEOYTKcdQ3cGgmPE2qgWS0iGqL3GZYdA7Qyx7mspiTYmPyx34Sed42mf9rrTVk9AxzH5urdXFNEDpqBkyXbEmyUdUuB1DiMf1+4XhdFwryfOkySfZR8+UQIPZ2cS4HF8KYGbwq/Kkag9CKKkUAeDcn1AFJ3ZC07HJTH7w7lD1LNEVgM/c0EA/3isz5+s8DNbX9ltbGUVgyi8vnMDPGOM9zMBa4IBx7rPEJLYKekOxtqZj/vNPb9qxCN1sOquiPCyANJB35dMJsdUdpXl+OVvHPLBz/tILMn2p7dkw60sw2f+aup7iQAVQRweqfWClbKoQlJZZ7oEeClxiCBfFrJryxeWF8VuYy04l0kLUpTAaGQF6HyFoAb1BlORtwGLdbGan+W8H5oux4XIrfD8djXoOL0feJE="

